app1/urls.py
from django.urls import path
from app1.views import *

app_name='CSK'
urlpatterns=[
    path('team1/',team1,name='team1')
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='RCB'
urlpatterns=[
    path('team2/',team2,name='team2')
]

project15/urls.py
from django.contrib import admin
from django.urls import path,include
from app3.views import *
import app1
import app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lead/',lead,name='lead'),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls'))
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render


def team1(request):
    return render(request,'team1.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def team2(request):
    return render(request,'team2.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def lead(request):
    return render(request,'lead.html')

templates/lead.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        #one
        {
            background-color: yellow;
            color: blue;
        }
        #two
        {
            background: rgb(red, green, blue);
            color: rgb(250, 79, 11);
        }
    </style>
    <title>Document</title>
</head>
<body>
    <center>
        <h1 id="one">welcome</h1>
        <h1 id="two">CSK VS RCB</h1>
        <h2>CSK CAPTAIN DHONI</h2>
        <img src="https://tse3.mm.bing.net/th?id=OIP.5ITfbLwzdfuMhadQNfIMcAHaFj&pid=Api&P=0" alt=""><br>
        <a href="{% url 'CSK:team1' %}">csk members</a>
        <h2>RCB CAPTION VIRAT</h2>
        <img src="https://tse4.mm.bing.net/th?id=OIP.dYWvYkXgj1jP66ZZ6PzY0QHaGc&pid=Api&P=0" alt=""><br>
        
        <a href="{% url 'RCB:team2' %}">RCB members</a>
    </center>
</body>
</html>

templates/team1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>CSK TEAM </h1>
        <a href="{% url 'lead' %}">match</a>
    </center>
</body>
</html>

templates/team2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>RCB TEAM</h1>
        <a href="{% url 'lead' %}">match</a>
    </center>
</body>
</html>